DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS meds;
DROP TABLE IF EXISTS foods;
DROP TYPE IF EXISTS types;
DROP TYPE IF EXISTS classes;

DROP EXTENSION IF EXISTS "uuid-ossp";