
DROP TABLE IF EXISTS meds CASCADE;
DROP TABLE IF EXISTS foods CASCADE;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS dogs CASCADE;
DROP TABLE IF EXISTS dogs_meds CASCADE;
DROP TABLE IF EXISTS dogs_foods CASCADE;
DROP TYPE IF EXISTS types;
DROP TYPE IF EXISTS classes;

DROP EXTENSION IF EXISTS "uuid-ossp";